### Get Access Token (Cloud Foundry using Client Credentials)
# @name requestAccessToken
POST {{$dotenv graph_tokenendpoint}}/oauth/token
Authorization: Basic {{$dotenv graph_clientid}}:{{$dotenv graph_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=client_credentials
&response_type=token

### Fill Variables from Response
#@access_token = {{requestAccessToken.response.body.$.access_token}}
# Use Access Token from external source
#@access_token={{$dotenv token}}

### Request Access Token
# @name requestAccessToken
POST {{$dotenv graph_tokenendpoint}}/oauth/token
Accept: application/json
Authorization: Basic {{$dotenv graph_clientid}}:{{$dotenv graph_clientsecret}}
Content-Type: application/x-www-form-urlencoded

grant_type=password
&username={{$dotenv username}}
&password={{$dotenv password}}
&client_id={{$dotenv graph_clientid}}
&response_type=token
#&login_hint={"origin":"sap.custom"}
### Fill Variables from Response
@access_token = {{requestAccessToken.response.body.$.access_token}}
@id_token = {{requestAccessToken.response.body.$.id_token}}
###

###
GET {{$dotenv graph_uri}}
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/catalog
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/config
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}
Authorization: Bearer {{access_token}}
### For S/4HANA start here
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}/sap.s4
Authorization: Bearer {{access_token}}
### Request OpenAPI specification
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}/sap.s4/A_SalesOrder
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.ecc.vh/PlantSet
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.user
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.user/UserDetailsSet
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/$metadata
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/A_BusinessPartner
  ?$top=10
  &$skip=10
  &$count=true
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/A_BusinessPartnerAddress
  ?$top=10
  &$count=true
  &$filter=Country eq 'DE'
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/A_BuPaAddressUsage
  ?$top=10
  &$count=true
  &$filter=AddressUsage ne 'XXDEFAULT'
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/A_Product
  ?$top=10
  &$select=Product,Brand,CountryOfOrigin
  &$count=true
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/A_SalesOrder
  ?$top=10
  &$expand=to_Item,to_Partner($expand=to_Address)
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/A_CompanyCode
  ?$top=10
Authorization: Bearer {{access_token}}
###
@BusinessObjectTypeName=BUS1001006
@material=FG011
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/GetAttachmentCount(SAPObjectNodeType='',SAPObjectType='',SemanticObject='',LinkedSAPObjectKey='{{material}}',BusinessObjectTypeName='{{BusinessObjectTypeName}}')
Authorization: Bearer {{access_token}}
###
# @name getAllOriginals
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/GetAllOriginals(SAPObjectNodeType='',SAPObjectType='',SemanticObject='',LinkedSAPObjectKey='{{material}}',BusinessObjectTypeName='{{BusinessObjectTypeName}}')
Authorization: Bearer {{access_token}}
### Map Response to Variable
@DMSDocumentInfoRecordDocType={{getAllOriginals.response.body.value[0].DocumentInfoRecordDocType}}
@DMSDocumentInfoRecordDocNumber={{getAllOriginals.response.body.value[0].DocumentInfoRecordDocNumber}}
@DMSLogicalDocument={{getAllOriginals.response.body.value[0].LogicalDocument}}
@DMSArchiveDocumentID={{getAllOriginals.response.body.value[0].ArchiveDocumentID}}
@DMSLinkedSAPObjectKey={{getAllOriginals.response.body.value[0].LinkedSAPObjectKey}}
@DMSBusinessObjectTypeName={{getAllOriginals.response.body.value[0].BusinessObjectTypeName}}
### Read created document Metadata:
### Resource not found for the segment 'blob'
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/AttachmentContentSet(DocumentInfoRecordDocType='{{DMSDocumentInfoRecordDocType}}',DocumentInfoRecordDocNumber='{{DMSDocumentInfoRecordDocNumber}}',DocumentInfoRecordDocVersion='',DocumentInfoRecordDocPart='',LogicalDocument='{{DMSLogicalDocument}}',ArchiveDocumentID='{{DMSArchiveDocumentID}}',LinkedSAPObjectKey='{{DMSLinkedSAPObjectKey}}',BusinessObjectTypeName='{{DMSBusinessObjectTypeName}}')
Authorization: Bearer {{access_token}}
Accept: application/json
### Read created document Content
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/sap.s4/AttachmentContentSet(DocumentInfoRecordDocType='{{DMSDocumentInfoRecordDocType}}',DocumentInfoRecordDocNumber='{{DMSDocumentInfoRecordDocNumber}}',DocumentInfoRecordDocVersion='',DocumentInfoRecordDocPart='',LogicalDocument='{{DMSLogicalDocument}}',ArchiveDocumentID='{{DMSArchiveDocumentID}}',LinkedSAPObjectKey='{{DMSLinkedSAPObjectKey}}',BusinessObjectTypeName='{{DMSBusinessObjectTypeName}}')/$value
Authorization: Bearer {{access_token}}
Accept: application/json
###
### SAP ERP Backend requests
###
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}/my.erp.bp/
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}/my.erp.bp/ZA_BusinessPartner
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}/my.erp.bp/ZA_Customer
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}/my.erp.bp/ZA_Supplier
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/catalog/{{$dotenv graph_name}}/my.erp.bp/ZA_BusinessPartnerAddress
Authorization: Bearer {{access_token}}
### URL from the OpenAPI specification
### returns:
### cannot route request, no match found for path /catalog/my.erp.bp
GET https://eu10.graph.sap/catalog/my.erp.bp
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.erp.bp
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.erp.bp/$metadata
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.erp.bp/ZA_BusinessPartner
  ?$top=10
  &$count=true
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.erp.so
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.erp.so/$metadata
Authorization: Bearer {{access_token}}

###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.erp.so/ZA_SalesOrderHeaderPartner
  ?$filter=PartnerFunction eq 'ZZ'
  &$top=10
Authorization: Bearer {{access_token}}

###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.erp.so/ZA_SalesOrder
  ?$top=10
  &$filter=SalesOrder eq '{{$dotenv SalesOrder}}'
  &$expand=to_Item($select=FunctionalLocation),to_Partner($expand=to_Address($select=Country,FullName))
  // This query:
  // to_Partner($filter=PartnerFunction eq 'ZZ')
  // returns:
  // The OData V2 API for entity 'ZA_SalesOrder' does not support $filter or $orderby on expanded properties.
  &$select=SalesOrder
Authorization: Bearer {{access_token}}
### EPM
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.epm/$metadata
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.epm/
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.epm/Suppliers
  ?$top=10
Authorization: Bearer {{access_token}}
### ZBP_SRV
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/$metadata
Authorization: Bearer {{access_token}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/
Authorization: Bearer {{access_token}}
###
# @name readBP
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/BPAddressSet
Authorization: Bearer {{access_token}}
###
@bpID={{readBP.response.body.$.value[0].Partner}}
###
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/BPAddressSet('{{bpID}}')
Authorization: Bearer {{access_token}}
###
# @name readAttachments
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/BPAddressSet
  ?$expand=to_Attachments($select=DocId)
  &$select=Partner,NameOrg1
Authorization: Bearer {{access_token}}
###
@DocId={{readAttachments.response.body.$.value[0].to_Attachments[0].DocId}}
###
# Is translated to backend request:
# /sap/opu/odata/sap/ZBP_SRV/BPAttachmentSet(Partner='1',DocId='FOL41000000000004EXT49000000000092')?$select=Content,Partner,DocId
# And results in: 
# Error during request to remote service: Method 'BPATTACHMENTSET_GET_ENTITY' not implemented in data provider class
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/BPAttachmentSet(Partner='{{bpID}}',DocId='{{DocId}}')/Content
Authorization: Bearer {{access_token}}
###
# Is translated to backend request:
# /sap/opu/odata/sap/ZBP_SRV/BPAttachmentSet(Partner='1',DocId='FOL41000000000004EXT49000000000092')?$select=blob,Partner,DocId
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/BPAttachmentSet(Partner='{{bpID}}',DocId='{{DocId}}')/blob
Authorization: Bearer {{access_token}}
###
# Is translated to backend request:
# /sap/opu/odata/sap/ZBP_SRV/BPAttachmentSet(Partner='1',DocId='FOL41000000000004EXT49000000000092')?$select=blob
GET {{$dotenv graph_uri}}/api/{{$dotenv graph_name}}/my.a4h.bp/BPAttachmentSet(Partner='{{bpID}}',DocId='{{DocId}}')/$value
Authorization: Bearer {{access_token}}